on:
  push:
    branch:
      - 'main'
name: deploy
jobs:
  deploy_web:
    name: Deploy Web
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      content: write
    steps:
      - uses: actions/checkout@v2
      - uses: jetli/wasm-pack-action@v0.4.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build Web
        run: make
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: playground